name: angelaspink
favicon: null
layout_spectrum: 0.16864709951914847
typography_spectrum: 0.6823688363656402
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9573064225260168
  lightness: 0.4132463096175343
  saturation: 0.9539893639739603
  rhythmicContrast: 0.36393212573602796
purpose: []
